project:
  type: website

website:
  title: "Giacomo Bignardi, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - posts.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

