---
title: "CV"
toc: false
---

# Previous Employment

-   2025+ Postdoctoral Research Associate
    -   INHERIT Lab, Social, Genetic & Developmental Psychiatry Centre, King's College London
-   2023-2025 Postdoctoral By-Fellow
    -   [Churchill College, Cambridge](https://www.chu.cam.ac.uk/fellows/dr-giacomo-bignardi/)
-   2022-2025: Postdoctoral Research Associate
    -   Department of Psychology, University of Cambridge
    -   [Developmental Cognitive Neuroscience Lab](https://sites.google.com/site/blakemorelab/)
-   2017-2021: PhD Studentship
    -   Funded PhD Scholarship with [4D Lab](https://www.astlelab.com/)
-   2015-2017
    -   Research Assistant, Institute of Public Health, University of Cambridge
    -   [The Behaviour and Health Research Unit (BHRU)](https://www.bhru.iph.cam.ac.uk/)

# Education

-   PhD, MRC Cognition and Brain Sciences Unit, University of Cambridge, 2021
-   MRes in Animal Behaviour, Newcastle University (UK), 2015
-   MA in Politics, Psychology & Sociology, University of Cambridge, 2014
-   Mathematical Statistics (M347 - 30 credit module), Open University, 2020.
